---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx1-index
data:
  index.html: |
    <html>
    <head>
            <title>Test NGINX V1 passed</title>
    </head>
    <body>
    <h1>NGINX V1 is working</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx
        image: quay.io/borland6/nginx-unprivileged
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx1-index
          #mountPath: /opt/app-root/src
          mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx1-index
          configMap:
            name: nginx1-index
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-1
spec:
  selector:
    app: nginx-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
